Feature: failing test
  In order to test this issue
  As a tester
  I need to get the exception

  Scenario: --
    When exception is thrown
